import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "../providers/AuthProvider";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";



const poppins = Poppins({
  weight: "500",
  subsets: ["latin"],
   style: "italic",
});
export const metadata: Metadata = {
  title: "My Protfolio App",
  description: "Generated by create Rakibul Hasan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Toaster/>
          <main className="min-h-dvh"> {children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
